# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tmp',
            new_name='team',
        ),
    ]
