# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170708_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='replies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='retweets',
            field=models.IntegerField(null=True),
        ),
    ]
