# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170708_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='favs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='replies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='retweets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='tags.NewsPaper'),
        ),
    ]
