# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170708_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tweet_source',
            new_name='social_source',
        ),
    ]
