# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170708_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fb_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
