# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0006_auto_20170709_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goals_home', models.IntegerField()),
                ('Goals_away', models.IntegerField()),
                ('Date_game', models.DateTimeField()),
                ('tag', models.CharField(max_length=10)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
            options={
                'ordering': ['-Date_game'],
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_event', to='stats.GameEvent')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('postition', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='tags.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('season', models.CharField(max_length=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_team', to='tags.Team')),
            ],
        ),
        migrations.AddField(
            model_name='gameevents',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='Event',
            field=models.ManyToManyField(through='stats.GameEvents', to='stats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='Stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Stadium'),
        ),
        migrations.AddField(
            model_name='game',
            name='Team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tags.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='Team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tags.Team'),
        ),
    ]
