# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20170709_1738'),
        ('stats', '0003_auto_20170710_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('european', models.BooleanField()),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.League')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='stats.Competition'),
        ),
    ]
