# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170710_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='stats.Competition'),
        ),
    ]
