# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20170710_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='teamstats',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_stats', to='stats.Competition'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
    ]
