# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_competition_league_flg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['Date_game']},
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
