# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20170711_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='alexander-lacazette'),
        ),
    ]
