# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('paper_url', models.URLField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('other_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.League')),
                ('newspaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.NewsPaper')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='tags.League')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Team'),
        ),
    ]
