# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
