# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_team_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='default'),
        ),
    ]
