# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tags_negative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='negative',
        ),
    ]
